@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\CAD\IAR\EWARMv630\common\bin\cspybat" "D:\CAD\IAR\EWARMv630\arm\bin\armproc.dll" "D:\CAD\IAR\EWARMv630\arm\bin\armjlink.dll"  %1 --plugin "D:\CAD\IAR\EWARMv630\arm\bin\armbat.dll" --macro "D:\CAD\IAR\EWARMv630\arm\config\debugger\ST\Trace_STM32F1xx.dmac" --flash_loader "D:\CAD\IAR\EWARMv630\arm\config\flashloader\ST\FlashSTM32F10xxB.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "D:\CAD\IAR\EWARMv630\arm\CONFIG\debugger\ST\iostm32f10xxB.ddf" "--drv_verify_download" "--semihosting" "--device=STM32F103xB" "--drv_communication=USB0" "--jlink_speed=auto" "--jlink_initial_speed=5" "--jlink_reset_strategy=0,0" "--drv_catch_exceptions=0x000" "--drv_swo_clock_setup=72000000,0,2000000" 


